version: "3"
services:
    bot:
        image: container.apps.mixify.ga/yinyangdiscordbot/bot:latest
        build: ./services/bot
        restart: always
        links:
            - database
        environment:
            DISCORD_TOKEN: ${DISCORD_TOKEN}

    database:
        build:
            context: ./services/database
        image: container.apps.mixify.ga/yinyangdiscordbot/database:latest
        volumes:
            - ./.data/database:/var/lib/postgresql/data
        restart: always
